CREATE DATABASE "Todo";

CREATE TABLE "Todos" (
    "ID" SERIAL PRIMARY KEY,
    "TItle" TEXT NOT NULL,
    "Description" TEXT NOT NULL,
    "CreatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "LastModified" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
);

CREATE TABLE "Users" (
    "ID" SERIAL PRIMARY KEY,
    "FirstName" TEXT NOT NULL,
    "LastName" TEXT NOT NULL,
    "Email" TEXT NOT NULL UNIQUE,
    "Phone" TEXT NOT NULL,
    "HashedPassword" TEXT NOT NULL,
    "CreatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "LastModified" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

